//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _41MY_MVCWebSiteCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Education
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubHeading { get; set; }
        public string SubHeading2 { get; set; }
        public string GPA { get; set; }
        public string Date { get; set; }
    }
}
